version: 2
updates:
  - package-ecosystem: gradle
    directory: /jetbrains
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /vscode
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
